"""Aggregate per-component outputs into a single statistical panel.

Consumes the JSON outputs from the other scripts and produces:

- panel.json   - structured per-corpus report.
- panel.tex    - LaTeX tables ready for thesis appendix.
- checklist.md - reporting-checklist (statistical_protocol.md section 4)
                 with PASS/FAIL per item based on artifact presence.

The optional --mirror-to flag also copies the figures to a sibling
directory (e.g. ~/PhD/figures/) for thesis-build integration.

CLI:
    python -m scripts.statistical_analysis.aggregate_panel \\
        --corpus non_human \\
        --in-dir results/statistical/non_human \\
        --out-json results/statistical/non_human/panel.json \\
        --out-tex results/statistical/non_human/panel.tex \\
        --out-checklist results/statistical/non_human/checklist.md
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

from . import MODELS, PRIMARY_METRICS

CHECKLIST_ITEMS = [
    ("All four metrics (MCC, AUROC, F1, AUPRC), mean +/- sigma",
     "effect_size.json", "by_metric"),
    ("Paired bootstrap IC95 per pair (Wilcoxon p)",
     "tost.json", "ordered_pair_results"),
    ("Hedges' g paired (J(4) primary) per pair",
     "effect_size.json", "primary_form"),
    ("Null-model lower limit per corpus",
     "null_model.json", "metrics"),
    ("Assay-noise upper limit per corpus",
     "upper_limit.json", "metrics"),
    ("TOST sensitivity over >= 3 bands",
     "tost.json", "by_band"),
    ("RM-ANOVA + Tukey HSD per metric (D2 complement)",
     "anova_tukey.json", "by_metric"),
    ("Simultaneous CI plot (figures/sim_ci_*.pdf)",
     "figures", "sim_ci"),
    ("MCSim heatmap (figures/mcsim_*.pdf)",
     "figures", "mcsim"),
    ("Post-hoc classification metrics (precision@recall, recall@precision, TNR@recall)",
     "posthoc.json", "by_model"),
]


def _safe_load(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        with path.open() as fh:
            return json.load(fh)
    except json.JSONDecodeError:
        return None


def _figures_present(in_dir: Path, prefix: str) -> bool:
    figs_dir = in_dir / "figures"
    if not figs_dir.exists():
        return False
    return bool(list(figs_dir.glob(f"{prefix}_*.pdf")))


def _evaluate_checklist(in_dir: Path) -> list[dict]:
    rows = []
    for description, source, key in CHECKLIST_ITEMS:
        if source == "figures":
            ok = _figures_present(in_dir, key)
            evidence = f"figures/{key}_*.pdf"
        else:
            data = _safe_load(in_dir / source)
            ok = data is not None and key in data
            evidence = source
        rows.append({"description": description, "evidence": evidence,
                     "pass": bool(ok)})
    return rows


def _format_latex_summary(panel: dict) -> str:
    lines = []
    lines.append(r"% Statistical panel auto-generated by aggregate_panel.py")
    lines.append(r"% Source: results/statistical/{corpus}/panel.json")
    lines.append("")
    lines.append(r"\begin{table}[ht]")
    lines.append(r"  \centering")
    lines.append(r"  \begin{tabular}{lcccc}")
    lines.append(r"    \toprule")
    lines.append(r"    Model & MCC & AUROC & F1 & AUPRC \\")
    lines.append(r"    \midrule")
    eff = panel.get("effect_size")
    if eff:
        for m in MODELS:
            cells = []
            for metric in ("mcc", "auroc", "f1", "auprc"):
                pm = eff["by_metric"][metric]["per_model"][m]
                cells.append(f"{pm['mean']:.4f} $\\pm$ {pm['std']:.4f}")
            lines.append(
                f"    {m.replace('_', '-')} & " + " & ".join(cells) + r" \\")
    lines.append(r"    \midrule")
    null = panel.get("null_model")
    if null:
        cells = []
        for metric in ("mcc", "auroc", "f1", "auprc"):
            mm = null["metrics"][metric]
            cells.append(f"{mm['median']:.4f}")
        lines.append(r"    Null model (lower limit) & " + " & ".join(cells) + r" \\")
    upper = panel.get("upper_limit")
    if upper:
        cells = []
        for metric in ("mcc", "auroc", "f1", "auprc"):
            mm = upper["metrics"][metric]
            cells.append(f"{mm['median']:.4f}")
        lines.append(r"    Assay upper limit & " + " & ".join(cells) + r" \\")
    lines.append(r"    \bottomrule")
    lines.append(r"  \end{tabular}")
    lines.append(rf"  \caption{{Statistical panel, corpus = {panel['corpus']}.}}")
    lines.append(rf"  \label{{tab:stat-panel-{panel['corpus']}}}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def _format_checklist(panel: dict, checklist_rows: list[dict]) -> str:
    lines = []
    lines.append(f"# Reporting checklist - corpus {panel['corpus']}")
    lines.append("")
    lines.append("Source: `docs/01-methodology/statistical_protocol.md` section 4.")
    lines.append("This file is auto-generated by `aggregate_panel.py`.")
    lines.append("")
    lines.append("| Item | Evidence | Status |")
    lines.append("|---|---|:---:|")
    for r in checklist_rows:
        status = "PASS" if r["pass"] else "FAIL"
        lines.append(f"| {r['description']} | `{r['evidence']}` | {status} |")
    lines.append("")
    n_pass = sum(1 for r in checklist_rows if r["pass"])
    lines.append(f"**Summary:** {n_pass}/{len(checklist_rows)} items PASS.")
    lines.append("")
    lines.append("Three deviations are declared and preserved (see "
                 "`docs/01-methodology/statistical_protocol.md` section 2):")
    lines.append("- D1: single scaffold split + 5 seeds (no 5x5 CV).")
    lines.append("- D2: paired bootstrap is primary; ANOVA + Tukey HSD complementary.")
    lines.append("- D3: TOST band 0.05 MCC SESOI-anchored (primary); "
                 "Cohen-anchored bands reported as sensitivity.")
    return "\n".join(lines)


def aggregate(corpus: str, in_dir: Path,
              out_json: Path, out_tex: Path,
              out_checklist: Path,
              mirror_to: Path | None = None) -> dict:
    panel = {
        "corpus": corpus,
        "models": list(MODELS),
        "primary_metrics": list(PRIMARY_METRICS),
        "null_model": _safe_load(in_dir / "null_model.json"),
        "upper_limit": _safe_load(in_dir / "upper_limit.json"),
        "posthoc": _safe_load(in_dir / "posthoc.json"),
        "effect_size": _safe_load(in_dir / "effect_size.json"),
        "anova_tukey": _safe_load(in_dir / "anova_tukey.json"),
        "tost": _safe_load(in_dir / "tost.json"),
    }

    checklist_rows = _evaluate_checklist(in_dir)
    panel["checklist"] = checklist_rows

    out_json.parent.mkdir(parents=True, exist_ok=True)
    with out_json.open("w") as fh:
        json.dump(panel, fh, indent=2)

    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(_format_latex_summary(panel))

    out_checklist.parent.mkdir(parents=True, exist_ok=True)
    out_checklist.write_text(_format_checklist(panel, checklist_rows))

    if mirror_to is not None:
        mirror_to.mkdir(parents=True, exist_ok=True)
        figs_src = in_dir / "figures"
        if figs_src.exists():
            for fig in figs_src.glob("*.pdf"):
                shutil.copy2(fig, mirror_to / f"stat_{corpus}_{fig.name}")
            for fig in figs_src.glob("*.png"):
                shutil.copy2(fig, mirror_to / f"stat_{corpus}_{fig.name}")

    return panel


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus", required=True, choices=("human", "non_human", "all"))
    ap.add_argument("--in-dir", type=Path, required=True)
    ap.add_argument("--out-json", type=Path, required=True)
    ap.add_argument("--out-tex", type=Path, required=True)
    ap.add_argument("--out-checklist", type=Path, required=True)
    ap.add_argument("--mirror-to", type=Path, default=None,
                    help="Optional: copy figures to this directory "
                         "(e.g. ~/PhD/figures/) for thesis build.")
    args = ap.parse_args()
    panel = aggregate(args.corpus, args.in_dir, args.out_json,
                     args.out_tex, args.out_checklist, args.mirror_to)
    n_pass = sum(1 for r in panel["checklist"] if r["pass"])
    n_total = len(panel["checklist"])
    print(f"[aggregate_panel] corpus={args.corpus} "
          f"checklist={n_pass}/{n_total} PASS")
    print(f"  json       -> {args.out_json}")
    print(f"  tex        -> {args.out_tex}")
    print(f"  checklist  -> {args.out_checklist}")


if __name__ == "__main__":
    main()
